# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DemoAlamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoAlamofire
  pod 'Alamofire', '~> 4.6'
  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'

  target 'DemoAlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
